### ISSUE TITLE
Update recovery times for certain skills (v1.22.1 update)

### ISSUE THREAD

**Issue by Caledor** [dl-stuff/dl#105]
From the news:

・We will shorten the amount of time players are unable to control the controlled adventurer immediately after using certain adventurer skills.
The affected adventurers and skills are as follows.
　Naveed's Crystalline Blades skill
　Lea's Road to Glory and Floral Revolution skills
　Albert's Lightning Burst skill (including while he is electrified)
　Yaten's Festival Dance skill
　Valerio's Amuse-bouche skill (in Appetizer Stance, Entrée Stance, and Dessert Stance)
　Tobias's Revelation's Purge skill
　Bellina's Renegade Shadowblaze skill
　Lazry's Smithy Spin skill
　Julietta's Impending Sky skill
　Curran's Circular Judgment skill
　Annelie's Stunning Display II and Stunning Display III skills
　Louise's Arrow Shower skill
　Hawk's Hunter's Creed II skill
　Student Maribelle's Study Break skill
　Lily's Glacial Blossom skill
　Cassandra's Violet Uproar skill

**Comment by Mushymato** [comment]
15718bc12a7e119daa8ab078cdcaa0c26739b2d9
