### ISSUE TITLE
Vida - Incorrect FS damage on alt FS (S2)

### ISSUE THREAD

**Issue by khalidakh** [dl-stuff/dl#110]
**Current behavior:** Damage from Vida's alt FS (S2) is doing less than 1/10 of the normal FS damage, which is 3x 47% = 141% damage

**Expected behavior:** Alt FS should be dealing 3x 57% (171%) damage for the normal FS hits and an additional 3x 11% (33%) from the extra knives being thrown, for a total of 204% damage.

Sim logs for reference (with the unimportant lines removed):
```
--- S2's alt FS is active
  23.283: debug           ,fs_alt on       ,3
  25.017: dmg             ,fs              ,223.268 
  26.250: dmg             ,fs              ,223.268 
  27.483: dmg             ,fs              ,223.268 

--- normal FS damage
  27.483: debug           ,fs_alt off      ,0
  28.717: dmg             ,fs              ,2861.888
  29.950: dmg             ,fs              ,2861.888
  31.183: dmg             ,fs              ,2861.888
```

**Comment by Mushymato** [comment]
9816d97567826356848f24976ba7cc81ba1e704e
