### ISSUE TITLE
Skill Charge not affected by Skill Haste

### ISSUE THREAD

**Issue by imxtrabored** [dl-stuff/dl#125]
Unsure of true in-game interaction, but wiki claims that skill haste affects skill charge (not skill regen)

https://dragalialost.gamepedia.com/Skill_Gauge_Charge_Up

Confirm in-game interaction and update if needed?

**Comment by khalidakh** [comment]
doesn't seem to be the case. left: no skill haste. right: 30% skill haste

![image](https://user-images.githubusercontent.com/8316630/89493611-9665bb00-d7c5-11ea-97ed-ea46e9e0c67c.png)

**Comment by imxtrabored** [comment]
Seems incorrect; closing for now
