### ISSUE TITLE
Consider team's Strength Doublebuff ability

### ISSUE THREAD

**Issue by khalidakh** [dl-stuff/dl#134]
Given that doublebuffs is seeing more prevalance in the game/meta lately, particularly in water (karina, s!celliera, and pipple) and shadow (patia), I believe this would make the adventurers that are usually involved in this mechanic to be more accurately represented.

of course, it should only be included on units that are relevant to them, like s!celliera, karina, t!hope, patia, and pipple.

**Comment by Mushymato** [comment]
absolute gains of running doublebuff print vs sd/punisher vary a lot per adventurer. For doublebuff I believe that the # of uses of the team def buff skill is as accurate as we can get, and this can be seen in the logs (e.g. 's1': 12) already.
