### ISSUE TITLE
Mana circle indication

### ISSUE THREAD

**Issue by NoctisCepheus** [dl-stuff/dl#142]
its kinda confusing to know if the sim is updated to a mana sprial or not. Is it possible to add a small detail for those with spirals unlocked? Like in the information section can it simply additionaly say "70mc" if the adventurer has 70mc unlocked?

**Comment by Mushymato** [comment]
It should be assumed that all characters are maxed out.
Of course there's a time gap to update the sim when characters are newly released but that's what Latest Updates are for, .
