### ISSUE TITLE
Most Staff Shared Skills set to S3 default to Weapon Skill

### ISSUE THREAD

**Issue by khalidakh** [dl-stuff/dl#151]
When the following adventurers' shared skill is set to S3, it defaults to the weapon skill:

- akasha
- cleo
- estelle
- halloween althemia
- hope
- jiang ziya
- lowen
- nurse aeleen
- ricardt
- summer verica
- valentines hildegarde
- verica
- vixel
- wedding xania

I tested other shared skills from other weapon types randomly, and only noticed this on staff units. hlowen and ycassandra are working fine.

EDIT: they work fine when set to S4. this issue happens only if set to S3.

**Comment by Mushymato** [comment]
6e8d28a1a7df66e1fe1c3bd369fdbfe76d6da8a5
