### ISSUE TITLE
Skill prep fails to initialize on shared skills

### ISSUE THREAD

**Issue by imxtrabored** [dl-stuff/dl#157]
![image](https://user-images.githubusercontent.com/14191445/91225997-07740080-e6ea-11ea-8a94-ed7382f5f94a.png)

This recent change from 6e8d28a1a7df66e1fe1c3bd369fdbfe76d6da8a5 to fix the healer skillsahre s3 issue also causes abilities to initialize after skillshares are initialized, which causes skill prep not to apply to shared skills. Skill prep users all lost a noticeable chunk of dps on the static chart.

**Comment by Mushymato** [comment]
4aafc1c66b8140b86d876612c0144836192f208a
