### ISSUE TITLE
Gala Cat Sìth 180% may be Skill Damage buffs (Not confirm)

### ISSUE THREAD

**Issue by peterfung727** [dl-stuff/dl#169]
Gala Cat Sìth 180% may be Skill Damage buffs. (Not confirm)

If 180% is buffs, Candy Couriers 40% (Skill Damage abilities) * Gala Cat Sìth 180% Skill Damage(Not 180%+40%), THX

**Comment by Mushymato** [comment]
gala cait sith is already implemented as skill damage buff.
