### ISSUE TITLE
Wind resistance down from Midgardsormr Zero 

### ISSUE THREAD

**Issue by LorentzB** [dl-stuff/dl#182]
Resistance down seems yet to be implemented in Sim 2.0.

BTW, is resistance change calculated as dmg * \prod(1 - delta_res), where delta_res is positive with res +x% prints and is negative when res lowered, as the damage formula on wikipage suggested?

**Comment by Mushymato** [comment]
Resistance down on mid0 is implemented as self buff only, for same reason as bog.
