### ISSUE TITLE
Some setups are not suited in game

### ISSUE THREAD

**Issue by Echoes-Feng** [dl-stuff/dl#184]
A lot of setups is just for high sim score, it can't use in game. For example, Veronica and GAlex. I think no one will use S!Patia's cex for GAlex. And no Veronica will use Durant's ss. I hope sim can show best or recommended setup for me to equip my character.

**Comment by Mushymato** [comment]
Simulator in it's current state is not suitable for recommending setups due to the assumption of a sandbag situation. I don't have a good solution for reconciling reality and felt that it's better to go with sim DPS first. In the future we may ban certain setups, like Durant.
