### ISSUE TITLE
Typo in Rena's S2

### ISSUE THREAD

**Issue by haukist** [dl-stuff/dl#186]
Rena's S2 buff lasts 20 sec but [Rena.json](https://github.com/dl-stuff/dl/blob/master/conf/adv/Rena.json) says:
```
{"buff": ["next", 0.5, 1, "crit", "damage"], "iv": 0.16667}
```
I guess her DPS is similar to Nobunaga or Aoi.

**Comment by Mushymato** [comment]
7578ce8ef487447bf3a153ddea8d41c6b60be939
