### ISSUE TITLE
Please add iOS cache support.

### ISSUE THREAD

**Issue by Parahexen** [dl-stuff/dl#188]
[https://developer.apple.com/library/archive/documentation/iPhone/Conceptual/SafariJSDatabaseGuide/OfflineApplicationCache/OfflineApplicationCache.html](https://developer.apple.com/library/archive/documentation/iPhone/Conceptual/SafariJSDatabaseGuide/OfflineApplicationCache/OfflineApplicationCache.html) 

So we could add it to the main screen as an offline web app.

**Comment by Mushymato** [comment]
Custom sim cannot be run offline by design, since the actual simulation work is done on server side. Chart could be cached offline but it would update slower I think.
