### ISSUE TITLE
Adventurers with custom combo + spiral

### ISSUE THREAD

**Issue by Caledor** [dl-stuff/dl#189]
Quick glance at the code so i'm not 100% sure.

When spiral is true for an adventurer it grabs the lv2 combo for the relevant weapons but what about adventurers with a personal combo chain and a spiral?

Writing this cause i noticed that Lily has Lv1 mods in "conf/adv/Lily.json" and i couldn't figure where the sim grabs lv2 mods.

PS: off topic but just noticed... pinon's S2 buff time is listed at 20 seconds but was increased to 40.

**Comment by Mushymato** [comment]
Unique combos
