### ISSUE TITLE
Doublebuff interval setting produces error

### ISSUE THREAD

**Issue by Sunspawn** [dl-stuff/dl#191]
When setting the doublebuff interval to any value, it gives the following error message:

Error: "Event" object has no attribute "source"

Link to screenshot: https://cdn.discordapp.com/attachments/646757922839199764/768128559985983518/unknown.png

**Comment by Sunspawn** [comment]
Did a quick test on an adventurer without any doublebuff effects and the sim worked fine.

**Comment by Mushymato** [comment]
dcd5b2ceb4b7333eef03795095b8c6c6591d7583
