### ISSUE TITLE
Filter Checkboxes

### ISSUE THREAD

**Issue by hovrawl** [dl-stuff/dl#202]
G'day,
Unsure if they new logic applied to the checkboxes to have them alternate check-all/check-one to show what you are filtering works quite well tbh, I understand it would have been applied to check all by default to SHOW what is the default view, however perhaps an ALL button on the side would be best to show the default state so when we check the element/weapon type it can still function more intuitively.
Appreciate the work gone into the UI and backend of the sims so far.

**Comment by Mushymato** [comment]
Reset is essentially the all button, will consider adjusting this to be more intuitive later
