### ISSUE TITLE
Formal Yoachim’s simulation - losing hits

### ISSUE THREAD

**Issue by TigerPPPPP** [dl-stuff/dl#203]
Hi, if I’m not mistaken, in practice Formal Yoachim needs to always have Meene on ex to keep hits, otherwise you lose hit counts when using s2 (even with refined Agito weapon, this remains the case). Not sure this is the same case with AI, but I would assume so. I believe the time gap between hitting the s2 bottom and when the hit connects is long enough no break hits.

**Comment by Mushymato** [comment]
sim formal joachim always uses s2 -> s1, which should keep combo at point blank.

**Comment by TigerPPPPP** [comment]
Hi Mushymato, thanks for your reply. I’ve tried it. S2 -> s1 at point blank, I kept “auto mode” so it will automatically release s1 after I manually release s2, which should resemble how AI runs it? But it loses combo every time. Maybe I somehow did it wrong. Anyway thanks!
