### ISSUE TITLE
[Request] Bleed uptime for adventurers and option to simulate bleed

### ISSUE THREAD

**Issue by Sunspawn** [dl-stuff/dl#205]
Could you please add bleed to the simulated afflictions (I know it is not, but we have a punisher print for it)? Ideally both as a simulated "someone else does" and an uptime % for what the adventurer afflicts for checking uptime with skillshares.

**Comment by ANASABDIALI** [comment]
It is really good program.
I really appreciate you.

**Comment by Mushymato** [comment]
closing this until bleed is meta
