### ISSUE TITLE
Arsene

### ISSUE THREAD

**Issue by tygis111** [dl-stuff/dl#209]
i don't have every dragon but i saw arsene had 90% unconditional skill damage. it would by nice to know how much damage i would loose from using him in an other element. like how much damage would my gala ranzal loss from using arsere instead of vayu or gala zephir? sorry if i posted this somewhere it didn't belong.

**Comment by Mushymato** [comment]
It can be napkin math'd by using vayu and multiplying result by (1+passive str)/(1.2+passive str).

Since 20 str/90 sd dragons are available as essence, there is no plan to make arsene available for off ele on web sim.
