### ISSUE TITLE
Hover wyrmprint ability details

### ISSUE THREAD

**Issue by caseyweederman** [dl-stuff/dl#212]
Nightstalker has 220 max might, comparable stats, and Lance's Boon. Lurker in the Woods is limited but is technically better by three strength, but worse by three HP. And I don't have it.
Juggling wiki pages on mobile is a pain and can terminate DL, tossing team changes.
Proposed change: wyrmprint ability details on popper div, and a long-press feature to simulate hover on mobile, so the user can pick an alternate print based on functionality.
Or: an option to have the auto print swapper to reject limited prints, since presumably that's what's choosing Lurker based on str>str.

**Comment by Mushymato** [comment]
dynamically replacing prints is impossible sorry

Many meta and not replacable prints/dragons are limited, so I don't particularly care to implement non limited/limited distinction. You are free to implement something and send in PR of course.

Lurker is identical to this non limited print https://dragalialost.wiki/w/Here_Come_the_Sealers!

**Comment by caseyweederman** [comment]
The purpose of this ticket was to request print details in the popper.js popups and a way to view them on mobile.
