### ISSUE TITLE
Gala Audric Has Implicit Negative Team Slice 

### ISSUE THREAD

**Issue by Balrix** [dl-stuff/dl#218]
1. GAudric Total DPS is not actually even close to the total, as shown here:
![GAudric 1](https://user-images.githubusercontent.com/73142251/128086258-a1ad0ee6-6290-4eb3-8431-b781ea803e0b.png)

Upon further inspection I noticed that the sim is actually substracting the team slice DPS from the total for some reason:
![GAudric 2 2](https://user-images.githubusercontent.com/73142251/128088570-4c93855b-0411-421d-beb5-5e03b040bb69.png)

So the reason the total Team DPS is 34014 is because it is doing 45542 - 11533 (team).  As would be expected from this behavior, increasing team DPS further lowers the Total DPS.

And by the way, I'm not sure where this team slice is even coming from, s1 and s2 are dps and affliction, a1 is def amp and att rate and a3 is od gauge accel.
 
2. The CSS breaks on second simulation and afterwards:
![GAudric 3](https://user-images.githubusercontent.com/73142251/128087414-0db53bcb-3c10-43a1-b591-bef7dd92ab75.png)

It also happens outside of Nihil, currently his BiS is weapon + Akasha, if Akasha gets deactivated in the ACL, the same issues that I stated above happen:
![GAudric 4](https://user-images.githubusercontent.com/73142251/128089929-3d0f7cd5-a5c0-4df6-af97-e235c150457d.png)

I set Team DPS to 150k - 300k. I'm using Firefox 90.0.2, but checked with Edge and there's the same issue.
This only happens with GAudric, don't have that problem with anyone else that I've checked.

**Comment by imxtrabored** [comment]
c1412d2f48ff21f9562eb1ce2990d8a890a34898
