### ISSUE TITLE
Naming Error in "First-Rate Hospitality"

### ISSUE THREAD

**Issue by Vbree13** [dl-stuff/dl#38]
The Wyrmprint "First-Rate Hospitality" is currently displaying as "FirstRate Hospitality", which results in a 404 page when attempting to click on its link to view its details page.

* Current URL: https://dragalialost.gamepedia.com/FirstRate_Hospitality
* Correct URL: https://dragalialost.gamepedia.com/First-Rate_Hospitality

Thank you for the amazing resource!

**Comment by Mushymato** [comment]
made a redirect
