### ISSUE TITLE
Bellina’s HP=1 simulation

### ISSUE THREAD

**Issue by TigerPPPPP** [dl-stuff/dl#41]
Hi, with respect to Bellina’s Hp=1 simulation, it seems that using s2 once at HP=1 shall suffice to generate enough DDP for activating dragon drive. In your simulation s2 are used twice before activating, which would cause significant loss in DPS. Just wondering if there’s any particular logic in that simulation? Much appreciated!

**Comment by TigerPPPPP** [comment]
Adding to above, using s2 once should theoretically generate 40% of the DDP gauge, but in reality based on the length of the gauge actually filled, it appears to be 50% instead of 40%? My guess is that you actually need 50% DPP to activate dragondrive and there’s a bug somewhere allowing s2 to generate just that, in which case using s2 twice in your simulation would make perfect sense.

**Comment by Mushymato** [comment]
confirmed empirically that you can shift after 1 s2 even without additional utp from hp loss

**Comment by TigerPPPPP** [comment]
Many thanks!
