### ISSUE TITLE
Dragon Damage on main screen

### ISSUE THREAD

**Issue by LX421** [dl-stuff/dl#42]
For units optimized around shapeshifting, is it possible to get that damage on the main screen? For most units shapeshifitng isn't optimal for DPS but stuff like Audric, Euden, etc gain a lot from dragon damage. A relevant example of how this is important is that the new dragon G&C is a stronger pick for Xain than Siren and even scales better with team DPS, but Siren is displayed because shapeshifting isn't taken into account. It just makes sense to me that dragon damage should be considered in these cases.

In any case, thanks for this awesome tool!

**Comment by Mushymato** [comment]
there are people helping me with that rn, soon:tm:
