### ISSUE TITLE
240s and/or 300s mode

### ISSUE THREAD

**Issue by NoctisCepheus** [dl-stuff/dl#50]
can we have modes up to 240 or 300s? eVolk, in pubs, last around 4 minutes so atleast 240s is justifiable. HMC can also last 240s in pubs as well.

**Comment by Mushymato** [comment]
Volk resist resets on phase shift, so it is closer to a 1:30 fight + 2:00 fight for purpose of affliction, in addition the simulator does account for average skill of players.

Please use the custom sim if you want to see what happens at longer simulation times.
