### ISSUE TITLE
The desktop view is too "zoomed in"

### ISSUE THREAD

**Issue by wayofdreams** [dl-stuff/dl#78]
After the latest updates, the default desktop view has been changed to display less adventurers on screen.

I understand that the number of icons besides adventurers portraits has increased significantly, which has taken a lot of screen space, but I would prefer to have a more compact view that showed more units at a time for easier comparison between close units. Maybe a setting could be added to toggle between view modes?

**Comment by Mushymato** [comment]
I don't know what a compact view would look like and you can just zoom out, but feel free to send any UI related pull req to https://github.com/dl-stuff/dlsim-vue
