### ISSUE TITLE
A Better build for tiki

### ISSUE THREAD

**Issue by ShadowofMine** [dl-stuff/dl#79]
Hello，I found a better build for Tiki just as follow picture：
![TIM图片20200701155041](https://user-images.githubusercontent.com/51400749/86218061-df1cc980-bbb2-11ea-90bd-6d7b63948fc8.png)

**Comment by Mushymato** [comment]
Tiki S2 is at risk of combo loss and her combo builds slowly, hence dagger (Dycleo) is the default.

**Comment by ShadowofMine** [comment]
Sorry, I really forgot about it, thanks for your reply！



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"mushy mato"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月3日(星期五) 上午8:44
收件人:&nbsp;"dl-stuff/dl"<dl@noreply.github.com&gt;;
抄送:&nbsp;"If never"<413362214@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dl-stuff/dl] A Better build for tiki (#79)





 
Tiki S2 is at risk of combo loss and her combo builds slowly, hence dagger (Dycleo) is the default.
