### ISSUE TITLE
Treatment Like Xander's

### ISSUE THREAD

**Issue by SnailRacer-0** [dl-stuff/dl#80]
Just as 10-stack Xander exists in the sim's "Special" section, may 10-stack Karina please be there as well for consistency?

  Speaking of Xander and Karina, now that they have access to self-buffing thanks to shared skills, may you please conspicuously incorporate buffs into their regular descriptions?  For example, if they both keep Gala Elisanne's shared skill, you can have their descriptions say "maintain buff(s)" just as Aldred description says "maintain dragondrive."  This change will facilitate customizing them, which be especially valuable to some because these two will get Mana Spirals soon.  Thank you.

**Comment by Mushymato** [comment]
Buff stack sim implemented in 79b50dcdeb996bcaaa7494756c06d29de63ecc4f

Xander exists in special solely because he has strikers, while karina does not.

**Comment by SnailRacer-0** [comment]
Oh, okay.  Well, since Rawn and Luther also have the Striker’s Strength abilities, may they be added to the Special section as well, esp. Luther since he’ll get a Mana Spiral soon?

                Also, I thank you for adding skill one boosts to Karina, Xander, etc.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
