### ISSUE TITLE
custom sim error

### ISSUE THREAD

**Issue by Sunspawn** [dl-stuff/dl#83]
When entering custom sim, in place of the sim results the following message is displayed:

"Error: __init__() got an unexpected keyword argument 'modifier'"

**Comment by Sunspawn** [comment]
Checked and it seems to only appear for some adventurers.

Saw it in water and fire adventurers' custom sims.

**Comment by Mushymato** [comment]
Fixed in a4c506d19f2b7485ce996ed4e5d20053fd7bf482
