### ISSUE TITLE
Xander rotation improvement

### ISSUE THREAD

**Issue by imxtrabored** [dl-stuff/dl#84]
use hunter sarisse s4 instead of ranzal s4
```
if self.born_ruler_1.get() and not self.born_ruler_2.get()
`dragon.act('c3 s end')
`s3
`s4
`s2
`s1
else
`dragon.act('c3 s end'), fsc
`s3, fsc or s
`s2, fsc or s
`s1, fsc or s
`fs, x=2
end
```
up to 700-800 dps improvement depending on simulated frostbite
maybe possible to improve further if you play with it

**Comment by Mushymato** [comment]
fixed in 7983b4e87d5ab5ed37bf0109b2af1f45d639340f
