### ISSUE TITLE
Pipple sim improves if you do not use Leviathan dragon skill

### ISSUE THREAD

**Issue by imxtrabored** [dl-stuff/dl#85]
per title. replace
```
`dragon
```
with
```
`dragon.act('c2 dodge c2 dodge c2 dodge c2 dodge c2 dodge c2 end')
```
improvement increases with no frostbite but goes away if bog res < 100

**Comment by Mushymato** [comment]
fixed in 7983b4e87d5ab5ed37bf0109b2af1f45d639340f
