### ISSUE TITLE
Mitsuba/Yurius dragon base selection in sim

### ISSUE THREAD

**Issue by buddhaimonia** [dl-stuff/dl#86]
Hi there,

I don't 100% how the sim decides which dragons to set for each adventurer in the sim, but if you run it for Mitsuba and Yurius both with G&C instead of Siren, that's clearly the better dragon based on pure DPS (obviously, not even taking into account G&C's AoE skill charge). 

I'm not sure if you take specific feedback for adventurers, but I thought it would be unhelpful to players right now deciding which adventurer to invest in for Fire Agito to see both of them lower than they actually are because everyone else has G&C set except for them (who have Siren). Obviously, Mitsuba doesn't need any help exactly but still, and Yurius is flying beneath the radar because of his sim base set. 

Anyway, thanks for taking my feedback either way!

**Comment by Mushymato** [comment]
0ad182e5f5aa075666d8738c9112dca2c01d6a8d
