### ISSUE TITLE
Ieyasu Coabilities/ACL

### ISSUE THREAD

**Issue by khalidakh** [dl-stuff/dl#91]
In the sim with afflictions 100%, Ieyasu is sitting at ~45k DPS, with wand, axe2, and bow CAs. Meanwhile, the custom sim has the CAs default to wand, axe2, and **dagger** (instead of bow), and gives a much higher DPS.

In regards to his ACL: Dragon (Cat Sith) needs to be used only when running out of Skillful Trickery charges, as his combo numbers goes up fast enough to keep the number of charges to last the three minute DPS sim duration. In addition, using FS in ieyasu's combo when S3 buff is active improves his DPS considerably (~2.5k increase).

Below is the ACL I used:
```
##Use Gala Cat Sith only when out of Skillful Trickery
#`dragon.act('c3 s end')
`s3, not self.s3_buff
`s1, self.s3_buff
`s2, x=5
`s4, fsc
`fs, x=5 and self.s3_buff
```
**Gear:** Agito weapon, Gala Cat Sith, Resounding Rendition, The Fires of Hate
**Coabilities:** Wand, Axe2, Dagger
**Conditions:** Poison uptime 100%
**S3:** Agito weapon
**S4:** Curran
**Total DPS:** 51208

**Comment by Mushymato** [comment]
a541413558051eaa3038fc5b8d3fbaeff97a1782
