### ISSUE TITLE
DPS sim without mana spiral 

### ISSUE THREAD

**Issue by Skyreader13** [dl-stuff/dl#92]
It would be great to have DPS sim that dont consider mana spiral for adventurer that already have one, mainly for new player because of their limited resource. 
Also its pretty hard (for new player especially) to rate adventurer dps. Those that have mana spiral have no DPS data that doent use their spiral.
I think there are few option to approach this

1. make toggle-able mana spiral button to enable/disable them
2. make entirely new DPS sim that doesnt use mana spiral

**Comment by Mushymato** [comment]
The DPS sim is not aimed at new players, since early game content is trivial.
