### ISSUE TITLE
Issue with Ieyasu’s simulation

### ISSUE THREAD

**Issue by TigerPPPPP** [dl-stuff/dl#93]
Hit there, there seems to be a minor issue with Ieyasu’s simulation. With the recent increase in the amount of SP blade’s c5 can generate, currently even without Bow ex, Ieyasu can still generate just enough SP for s1 with only c5+c4 (you need c5+c5 before without Bow ex). As such, you can replace Bow ex with Dagger ex for Ieyasu to simulate a more optimized DPS of approximately 48,000 (assuming 100% position uptime). The customization page reflects and runs that perfectly in its log. Or alternatively, keeping Bow ex as is, then you only need c5+c3 now to generate enough SP for s1, which for some reason, the customization page does not run correctly in its log. It still shows you need c5+c4. This might need certain adjustment from your end to test which one (Bow or Dagger ex) simulates relatively higher DPS.

**Comment by Mushymato** [comment]
a541413558051eaa3038fc5b8d3fbaeff97a1782
