### ISSUE TITLE
Summer Celliera build 

### ISSUE THREAD

**Issue by khalidakh** [dl-stuff/dl#94]
This build improves S!Celliera's personal DPS as well as her team buffs output over the current build by focusing on using her S2 and Patia shared skill as often as possible:

**- Dragon:** Gaibhne & Creidhne
**- Print 1:** Valiant Crown
**- Print 2:** Proper Maintenence
**- Skill 3:** Patia
**- Skill 4:** S!Luca
**- Coabilities:** S!Estelle, Renee, H!Sarisse
**- ACL:**
```
`dragon.act('c3 s end')
`s2
`s3
`s4,fsc
`s1,fsc
`fs, x=2
```

**DPS** (current DPS // old DPS):
```
-      0 Team DPS: 25825 // 24942
- 15,000 Team DPS: 34040 // 29856
- 30,000 Team DPS: 42255 // 34769
```

**Comment by Mushymato** [comment]
dc3805fdba21c37c3c9295fd0d8343aec331975b
