### ISSUE TITLE
Forte optimization

### ISSUE THREAD

**Issue by khalidakh** [dl-stuff/dl#96]
1- Change Wyrmprint 1 from "Resounding Rendition" to "Dragon and Tamer"

2- Change the ACL to:
```
`dragon.act('c3 s end'),x=5
`s3, not self.s3_buff
`s2
`s4
`s1
`fs, x=5
```
In the above ACL, S4 is moved to below S2, so S2 is prioritized, and dragon is delayed until C5.

DPS (40k Team DPS): After // Before
```
-   0% Poison: 36873 // 35327 (Using The Red Impulse in Wyrmprint 2)
- 100% Poison: 62056 // 60026 (Using The Fires of Hate in Wyrmprint 2)
```

**Comment by Mushymato** [comment]
dc3805fdba21c37c3c9295fd0d8343aec331975b
