### ISSUE TITLE
Lazry optimization

### ISSUE THREAD

**Issue by khalidakh** [dl-stuff/dl#97]
Currently, Lazry's shapeshift goes for the full duration, and doesn't end after the dragon skill. Below is the updated ACL with the shapeshift ending after skill:
```
if s1.check() and self.afflics.frostbite.timeleft()<7
`low_power
else
`high_power
end
`dragon.act('c3 s end'),s
`s3
`s1
`s2
`s4
```
DPS (After // Before) @ 30k Team DPS:
```
-   0% Afflic: 25199 // 22955
- 100% Afflic: 25835 // 23558 
```

**Comment by Mushymato** [comment]
dc3805fdba21c37c3c9295fd0d8343aec331975b
