### ISSUE TITLE
Updates to the Sim

### ISSUE THREAD

**Issue by DragonZarman** [dl-stuff/dl#98]
Hi, I first want to say that your tool helps out the community an incredible amount. Thank you for keeping this tool updated whenever a new feature or unit is released. That being said, I was wondering if you could implement a push notification system either through email or some other means so the community is able to see whenever there is a new update. Thank you for taking this into consideration. Keep up the great work!

p.s. Sorry for posting this as an "issue". I don't know how else I can reach you.

**Comment by khalidakh** [comment]
you can get notifications via the notifications settings of this github project in the top right of the page
![image](https://user-images.githubusercontent.com/8316630/88983654-af113500-d2dc-11ea-8b56-2cf8930718c9.png)

**Comment by DragonZarman** [comment]
Thank you! Sorry for bothering your workflow. I did not know this feature existed.
